package handlers

import (
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/jung-kurt/gofpdf"

	"heart-predict-backend/models"
)

var featureLabels = map[string]string{
	"age": "Age", "sex": "Sex",
	"chest_pain_type": "Chest Pain Type", "resting_bp_s": "Resting BP (mm Hg)",
	"cholesterol": "Cholesterol (mg/dL)", "fasting_blood_sugar": "Fasting Blood Sugar",
	"resting_ecg": "Resting ECG", "max_heart_rate": "Max Heart Rate (bpm)",
	"exercise_angina": "Exercise Angina", "oldpeak": "ST Depression (Oldpeak)",
	"ST_slope": "ST Slope",
}

func Report() gin.HandlerFunc {
	return func(c *gin.Context) {
		var req models.ReportRequest
		if err := c.ShouldBindJSON(&req); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{
				"error": "report_error", "message": "Invalid request body",
			})
			return
		}

		pdf := gofpdf.New("P", "mm", "A4", "")
		pdf.SetMargins(20, 20, 20)
		pdf.AddPage()

		// ── Header ─────────────────────────────────────────
		pdf.SetFillColor(15, 20, 35)
		pdf.Rect(0, 0, 210, 35, "F")
		pdf.SetTextColor(232, 237, 245)
		pdf.SetFont("Helvetica", "B", 18)
		pdf.SetY(10)
		pdf.CellFormat(0, 10, "HeartPredict — Risk Assessment Report", "", 1, "C", false, 0, "")
		pdf.SetFont("Helvetica", "", 9)
		pdf.SetTextColor(107, 122, 153)
		pdf.CellFormat(0, 8, "Generated: "+time.Now().Format("02 Jan 2006, 15:04 MST"), "", 1, "C", false, 0, "")

		// ── Risk summary box ───────────────────────────────
		pdf.SetY(44)
		riskColor := map[string][3]int{
			"High": {229, 62, 62}, "Medium": {246, 173, 85}, "Low": {56, 161, 105},
		}[req.Result.RiskLevel]
		pdf.SetFillColor(riskColor[0], riskColor[1], riskColor[2])
		pdf.SetTextColor(255, 255, 255)
		pdf.SetFont("Helvetica", "B", 14)
		pdf.Rect(20, 44, 170, 18, "F")
		pdf.SetY(48)
		pdf.CellFormat(170, 10,
			fmt.Sprintf("%s RISK  |  %s  |  Confidence: %s",
				strings.ToUpper(req.Result.RiskLevel),
				strings.ToUpper(req.Result.Category),
				req.Result.Confidence),
			"", 1, "C", false, 0, "")

		// ── Category Description ──────────────────────────
		if req.Result.CategoryDescription != "" {
			pdf.SetY(64)
			pdf.SetFont("Helvetica", "I", 10)
			pdf.SetTextColor(107, 122, 153)
			pdf.MultiCell(170, 5, req.Result.CategoryDescription, "", "C", false)
		}

		// ── Patient inputs ────────────────────────────────
		pdf.SetY(78)
		pdf.SetTextColor(30, 45, 71)
		pdf.SetFont("Helvetica", "B", 11)
		pdf.Cell(0, 8, "Patient Input Data")
		pdf.Ln(10)

		fields := req.PatientData.FieldMap()
		fieldOrder := []string{
			"age", "sex", "chest_pain_type", "resting_bp_s", "cholesterol",
			"fasting_blood_sugar", "resting_ecg", "max_heart_rate",
			"exercise_angina", "oldpeak", "ST_slope",
		}

		pdf.SetFont("Helvetica", "", 10)
		pdf.SetTextColor(50, 60, 80)
		col := 0
		for _, key := range fieldOrder {
			val := fields[key]
			label := featureLabels[key]
			if label == "" {
				label = key
			}
			x := 20.0 + float64(col)*90
			y := pdf.GetY()
			pdf.SetXY(x, y)
			pdf.SetFont("Helvetica", "B", 9)
			pdf.SetTextColor(107, 122, 153)
			pdf.CellFormat(85, 5, strings.ToUpper(label), "", 0, "L", false, 0, "")
			pdf.SetXY(x, y+5)
			pdf.SetFont("Helvetica", "", 11)
			pdf.SetTextColor(30, 45, 71)
			pdf.CellFormat(85, 7, fmt.Sprintf("%.4g", val), "", 0, "L", false, 0, "")
			col++
			if col == 2 {
				col = 0
				pdf.Ln(14)
			}
		}
		pdf.Ln(18)

		// ── Contributing factors ──────────────────────────
		pdf.SetFont("Helvetica", "B", 11)
		pdf.SetTextColor(30, 45, 71)
		pdf.Cell(0, 8, "Top Contributing Factors")
		pdf.Ln(10)

		impactColor := map[string][3]int{
			"high": {229, 62, 62}, "medium": {246, 173, 85}, "low": {56, 161, 105},
		}
		for _, rf := range req.Result.RiskFactors {
			ic := impactColor[rf.Impact]
			label := featureLabels[rf.Feature]
			if label == "" { label = rf.Feature }
			pdf.SetFont("Helvetica", "", 10)
			pdf.SetTextColor(50, 60, 80)
			pdf.CellFormat(80, 7, label, "", 0, "L", false, 0, "")
			pdf.CellFormat(30, 7, fmt.Sprintf("%.4g", rf.Value), "", 0, "L", false, 0, "")
			pdf.SetFillColor(ic[0], ic[1], ic[2])
			pdf.SetTextColor(255, 255, 255)
			pdf.SetFont("Helvetica", "B", 8)
			pdf.CellFormat(30, 7, strings.ToUpper(rf.Impact), "0", 1, "C", true, 0, "")
			pdf.SetTextColor(50, 60, 80)
		}
		pdf.Ln(8)

		// ── Disclaimer ────────────────────────────────────
		pdf.SetFillColor(245, 245, 245)
		pdf.Rect(20, pdf.GetY(), 170, 18, "F")
		pdf.SetY(pdf.GetY() + 3)
		pdf.SetFont("Helvetica", "I", 8)
		pdf.SetTextColor(107, 122, 153)
		pdf.MultiCell(170, 4.5,
			"DISCLAIMER: This report is generated by a student research project and does not constitute medical advice. "+
				"The prediction is based on a machine learning model and may not be accurate. "+
				"Always consult a qualified healthcare professional for medical decisions.",
			"", "L", false)

		// ── Stream PDF ───────────────────────────────────
		c.Header("Content-Type",        "application/pdf")
		c.Header("Content-Disposition", `attachment; filename="heart_risk_report.pdf"`)

		if err := pdf.Output(c.Writer); err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{
				"error": "report_error", "message": "Could not generate report",
			})
		}
	}
}
