"use client";

import * as React from "react";
import { 
  Search, 
  Download, 
  MoreHorizontal, 
  Eye, 
  Trash2, 
  ChevronLeft, 
  ChevronRight,
  History,
  Database,
  Clock,
  Plus
} from "lucide-react";
import { 
  Card, 
  CardContent, 
  CardDescription, 
  CardHeader, 
  CardTitle 
} from "@/components/ui/card";
import { 
  Table, 
  TableBody, 
  TableCell, 
  TableHead, 
  TableHeader, 
  TableRow 
} from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { 
  DropdownMenu, 
  DropdownMenuContent, 
  DropdownMenuItem, 
  DropdownMenuLabel, 
  DropdownMenuSeparator, 
  DropdownMenuTrigger 
} from "@/components/ui/dropdown-menu";
import { DashboardLayout } from "@/components/DashboardLayout";
import { getAssessments, AssessmentRecord } from "@/lib/api";
import { cn } from "@/lib/utils";
import Link from "next/link";

export default function RecordsPage() {
  const [records, setRecords] = React.useState<AssessmentRecord[]>([]);
  const [loading, setLoading] = React.useState(true);
  const [search, setSearch] = React.useState("");

  React.useEffect(() => {
    async function init() {
      try {
        const data = await getAssessments();
        setRecords(data);
      } catch (err) {
        console.error("Failed to fetch records", err);
      } finally {
        setLoading(false);
      }
    }
    init();
  }, []);

  const filteredRecords = React.useMemo(() => {
    return records.filter(r => 
      r.id.toLowerCase().includes(search.toLowerCase()) ||
      r.response.risk_level.toLowerCase().includes(search.toLowerCase())
    );
  }, [records, search]);

  if (loading) {
    return (
      <DashboardLayout>
        <div className="flex items-center justify-center h-64 text-muted-foreground animate-pulse font-mono uppercase tracking-[0.2em] text-xs">
          Accessing Encrypted Registry...
        </div>
      </DashboardLayout>
    );
  }

  return (
    <DashboardLayout>
      <div className="flex flex-col gap-8">
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 text-[0.65rem] font-bold tracking-[0.2em] text-accent uppercase font-mono mb-1">
              <Database className="h-3 w-3" /> Registry v4.2.1
            </div>
            <h1 className="text-4xl font-serif text-foreground tracking-tight">Clinical Assessment Records</h1>
            <p className="text-muted-foreground mt-2 italic max-w-lg">
              "Complete historical repository of all diagnostic triangulations and risk profiles generated by this terminal."
            </p>
          </div>
          <div className="flex gap-2">
            <Button variant="outline" className="gap-2">
              <Download className="h-4 w-4" /> Export CSV
            </Button>
            <Link href="/predict">
              <Button className="gap-2 bg-accent text-white hover:bg-accent/90">
                <Plus className="h-4 w-4" /> New Session
              </Button>
            </Link>
          </div>
        </div>

        <Card>
          <CardHeader className="pb-4">
            <div className="relative max-w-md">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input 
                placeholder="Search by ID or risk level..." 
                className="pl-10 bg-muted/20 border-none h-11" 
                value={search}
                onChange={(e) => setSearch(e.target.value)}
              />
            </div>
          </CardHeader>
          <CardContent>
            {filteredRecords.length === 0 ? (
              <div className="py-20 text-center flex flex-col items-center gap-4 border border-dashed rounded-xl">
                 <div className="h-12 w-12 rounded-full bg-muted/20 flex items-center justify-center text-muted-foreground">
                    <History className="h-6 w-6" />
                 </div>
                 <div className="space-y-1">
                    <p className="font-bold text-foreground">No records found</p>
                    <p className="text-sm text-muted-foreground">Try adjusting your search criteria.</p>
                 </div>
              </div>
            ) : (
              <Table>
                <TableHeader>
                  <TableRow className="hover:bg-transparent border-b border-muted">
                    <TableHead className="w-[120px]">Case ID</TableHead>
                    <TableHead>Assessment Date</TableHead>
                    <TableHead>Risk Profile</TableHead>
                    <TableHead>Key Biomarkers</TableHead>
                    <TableHead className="text-right">Probability</TableHead>
                    <TableHead className="w-[80px]"></TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {filteredRecords.map((rec) => (
                    <TableRow key={rec.id} className="group">
                      <TableCell className="font-mono font-bold text-xs">
                        {rec.id.toUpperCase()}
                      </TableCell>
                      <TableCell className="text-muted-foreground whitespace-nowrap">
                         <div className="flex items-center gap-2">
                            <Clock className="h-3 w-3" />
                            {new Date(rec.date).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' })}
                         </div>
                      </TableCell>
                      <TableCell>
                        <Badge 
                          variant={rec.response.risk_level === 'High' ? 'destructive' : rec.response.risk_level === 'Medium' ? 'warning' : 'success'}
                          className="px-2.5 py-0.5 rounded-full"
                        >
                          {rec.response.risk_level}
                        </Badge>
                      </TableCell>
                      <TableCell>
                        <div className="flex gap-2">
                          <Badge variant="outline" className="bg-muted/5 border-muted/20 text-[0.6rem] font-mono">
                            AGE: {rec.request.age}
                          </Badge>
                          <Badge variant="outline" className="bg-muted/5 border-muted/20 text-[0.6rem] font-mono">
                            CHO: {rec.request.cholesterol}
                          </Badge>
                          <Badge variant="outline" className="bg-muted/5 border-muted/20 text-[0.6rem] font-mono">
                            SBP: {rec.request.resting_bp_s}
                          </Badge>
                        </div>
                      </TableCell>
                      <TableCell className="text-right">
                         <div className="flex flex-col items-end gap-1">
                            <span className="font-mono font-bold text-foreground">{(rec.response.probability * 100).toFixed(1)}%</span>
                            <div className="w-20 h-1 bg-muted/20 rounded-full overflow-hidden">
                               <div 
                                 className={cn(
                                   "h-full transition-all duration-500",
                                   rec.response.risk_level === 'High' ? "bg-destructive" : rec.response.risk_level === 'Medium' ? "bg-amber-500" : "bg-emerald-500"
                                 )} 
                                 style={{ width: `${rec.response.probability * 100}%` }}
                               />
                            </div>
                         </div>
                      </TableCell>
                      <TableCell>
                        <DropdownMenu>
                          <DropdownMenuTrigger asChild>
                            <Button variant="ghost" size="icon" className="h-8 w-8 text-muted-foreground hover:text-foreground">
                              <MoreHorizontal className="h-4 w-4" />
                            </Button>
                          </DropdownMenuTrigger>
                          <DropdownMenuContent align="end">
                            <DropdownMenuLabel>Actions</DropdownMenuLabel>
                            <DropdownMenuSeparator />
                            <DropdownMenuItem className="gap-2 cursor-pointer">
                              <Eye className="h-4 w-4" /> View Details
                            </DropdownMenuItem>
                            <DropdownMenuItem className="gap-2 text-destructive cursor-pointer">
                              <Trash2 className="h-4 w-4" /> Archive
                            </DropdownMenuItem>
                          </DropdownMenuContent>
                        </DropdownMenu>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            )}
          </CardContent>
          <div className="bg-muted/10 p-4 border-t flex items-center justify-between">
            <div className="text-[10px] text-muted-foreground uppercase font-bold tracking-widest">
              Showing {filteredRecords.length} records
            </div>
            <div className="flex items-center gap-2">
              <Button variant="ghost" size="sm" disabled className="h-8 w-8 p-0">
                <ChevronLeft className="h-4 w-4" />
              </Button>
              <Button variant="ghost" size="sm" disabled className="h-8 w-8 p-0">
                <ChevronRight className="h-4 w-4" />
              </Button>
            </div>
          </div>
        </Card>
      </div>
    </DashboardLayout>
  );
}
